#
# Prerequisites:
#    $ brew install cloudflared

@base_url = {{$dotenv BASE_URL}}
@username = {{$dotenv USERNAME}}
@password = {{$dotenv PASSWORD}}
@patient_uuid = {{$dotenv PATIENT_UUID}}

### auth - only needed if making calls to roman_api endpoints
# @name login
POST {{base_url}}/api/physician/auth/login
Content-Type: application/json
Cf-Access-Token: {{$dotenv CF_ACCESS_TOKEN}}

{
    "email": "{{username}}",
    "password": "{{password}}"
}

###
@key = {{login.response.body.token_data.key}}
@path_param=Jerry
@energizer_id=14

### show PARAMS
GET {{base_url}}/parameters/{{path_param}}/?multi=5
snake-header: 'snake_header_value'
Content-Type: application/json



### list ENERGIZERS
GET {{base_url}}/energizers
Dev-Auth: fake
Content-Type: application/json



### retrieve an ENERGIZER
GET {{base_url}}/energizers/{{energizer_id}}
Dev-Auth: fake
Content-Type: application/json



### add a test message
POST {{base_url}}/svc/non-ro-pharmacies/any/messages
Dev-Auth: fake
Content-Type: application/json

{
    "prescriber_id": "doc 99999",
    "drug_id": "Drug-910",
    "status": "prescribed",
    "prescriber_order_number": "Ro-Plan-444444"
}



### retrieve a test message
GET {{base_url}}/svc/non-ro-pharmacies/any/messages/{{message_id}}
Dev-Auth: fake
Content-Type: application/json
Cf-Access-Token: {{$dotenv CF_ACCESS_TOKEN}}

