#!/bin/bash
set -e -u

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

# shellcheck disable=SC1090
. "$DIR/../.env"

cloudflared access login "$BASE_URL"
CF_ACCESS_TOKEN=$(cloudflared access token -app="$BASE_URL")
sed -i "" -e "s/CF_ACCESS_TOKEN=.*/CF_ACCESS_TOKEN=$CF_ACCESS_TOKEN/g" "$DIR/../.env"
